name: Run Python Script

on:
  workflow_dispatch:
    inputs:
      country_name:
        description: 'Country Name'
        required: true
        default: 'USA'
      end_year:
        description: 'End Year'
        required: true
        default: '2020'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Set a specific version that's compatible with all dependencies

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pycountry pandas numpy matplotlib tradingeconomics

    - name: Run script
      run: python main.py ${{ github.event.inputs.country_name }} ${{ github.event.inputs.end_year }}



